branch-defaults:
  master:
    environment: Sample-env
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: date-by-hate
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running Python 3.4
  default_region: us-west-2
  profile: bill-bunkum
  sc: git
